DROP TABLE IF EXISTS users;


 CREATE TABLE users(
      id SERIAL PRIMARY KEY,
      firstName VARCHAR(30) NOT NULL,
      lastName VARCHAR(30) NOT NULL,
      email VARCHAR(60) NOT NULL UNIQUE,
      password VARCHAR(255) NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );

